global:
    scrape_interval: 10s

scrape_configs:
   -  job_name: prometheus_master
      scrape_interval: 5s
      static_configs:
         -  targets: [localhost:9090]
      relabel_configs:
         -  target_label: site
            replacement: prod
   -  job_name: node_exporter_ubuntu
      scrape_interval: 5s
      static_configs:
         -  targets: [localhost:9100]
      relabel_configs:
         -  target_label: site
            replacement: prod
   -  job_name: blackbox
      metrics_path: /probe
      params:
          module: [http_2xx]
      static_configs:
         -  targets:
               -  http://10.0.2.15/wp-admin/
      relabel_configs:
         -  source_labels: [__address__]
            target_label: __param_target
         -  source_labels: [__param_target]
            target_label: instance
         -  target_label: __address__
            replacement: localhost:9115
         -  target_label: site
            replacement: prod
   -  job_name: mysqld_exporter
      scrape_interval: 5s
      static_configs:
         -  targets: [localhost:9104]
      relabel_configs:
         -  target_label: site
            replacement: prod
   -  job_name: php_fpm_exporter
      scrape_interval: 5s
      static_configs:
         -  targets: [localhost:9253]
      relabel_configs:
         -  target_label: site
            replacement: prod
   -  job_name: nginx_exporter
      scrape_interval: 5s
      static_configs:
         -  targets: [localhost:9113]
      relabel_configs:
         -  target_label: site
            replacement: prod
remote_write:
   -  url: http://localhost:8428/api/v1/write
